# Generated by Django 4.1 on 2022-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carouswl_image', models.ImageField(upload_to='photos/carousel')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
