# Generated by Django 4.1 on 2022-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
