# Generated by Django 4.1 on 2022-08-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='carouswl_image',
            new_name='carousel_image1',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='description',
        ),
        migrations.AddField(
            model_name='carousel',
            name='description1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='description2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
