# Generated by Django 4.1 on 2022-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_carouswl_image_carousel_carousel_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_image2',
            field=models.ImageField(null=True, upload_to='photos/carousel'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image1',
            field=models.ImageField(null=True, upload_to='photos/carousel'),
        ),
    ]
