# Generated by Django 4.1 on 2022-08-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_carousel_carousel_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='carousel_image1',
            new_name='carousel_image',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_image2',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='description2',
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
